invitations/urls.py
from django.urls import path, include
from . import views
# from rest_framework import routers
#
# router = routers.DefaultRouter()
# router.register('addresses', views.AddressViewSet)

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('cart/', views.cart, name='cart'),
    path('profil/', views.profil, name='profil'),
    path('address/', views.address, name='address-update'),
    path('history/', views.history, name='history'),
    path('checkout/', views.checkout, name='checkout'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.usersignup, name='signup'),
    path('login/', views.userlogin, name='login'),
    path('logout/', views.userlogout, name='logout'),
    path('checkout/', views.checkout, name='checkout'),
    path('about/', views.about, name='about'),
    # path('', include(router.urls)),
    #path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
]

morningsmell/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('invitations.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invitations/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Contact(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()
    phone = models.CharField(max_length=10, null=True, blank=True)
    title = models.CharField(max_length=30)
    message=models.TextField()
    m_date=models.DateTimeField(auto_now_add=True)#the date massage started no chande when updated

    def __str__(self):
        return f"{self.name}, {self.title}"

#class ExtendUser(User):
#    phone=models.CharField(blank=True, null=True, max_length=10)

User.add_to_class('phone',models.CharField(blank=True, null=True, max_length=10))

class Product(models.Model):
    Categories = (( 'LH', 'לחמניות'), ('HL','מוצרי חלב'), ('MZ','מיצים') ,  ('MA', 'מאפים'))

    category = models.CharField(max_length=20, choices=Categories)
    product_name = models.CharField(max_length=30)
    price = models.FloatField()
    picture = models.ImageField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.product_name

class Address(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    town = models.CharField(max_length=30, verbose_name='עיר')
    street = models.CharField(max_length=50, verbose_name='רחוב')
    house_num = models.IntegerField(verbose_name='מספר בית')
    apt_num = models.IntegerField(verbose_name='מספר דירה')
    level = models.IntegerField(verbose_name='קומה')
    enter = models.IntegerField(blank=True, null=True, verbose_name='קוד כניסה')

    def get_fields(self):
        for field in Address._meta.fields:
            yield field.verbose_name, field.value_to_string(self)

    def __str__(self):
        return f"{self.town}, {self.street}"

class ProdUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()

    weekDay = ((0,'יום ראשון'),(1,'יום שני'),(2,'יום שלישי'),(3,'יום רביעי'),(4,'יום חמישי'),(5,'יום שישי'))

    day = models.IntegerField(choices=weekDay)

    def __str__(self):
        return f"{self.user.username}, {self.product.product_name}"

    def price(self):
        return self.product.price * self.amount

class BuyHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def price(self):
        return self.product.price * self.amount

    def __str__(self):
        return f"{self.date}, {self.user.username}, {self.product.product_name}"

invitations/forms.py
from django import forms
from .models import Contact, Address, ProdUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from datetime import datetime as date

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='שם מלא:')
    email = forms.EmailField(label='כתובת מייל:')
    phone_regex = RegexValidator(regex=r'^\d{9,10}$', message="נא הכנס מספר טלפון כולל קידומת")
    phone = forms.CharField(validators=[phone_regex], max_length=10, label='מספר טלפון:', required=False)
    password1 = forms.CharField(label = 'בחר סיסמה:')
    password2 = forms.CharField(label = 'חזור על הסיסמה:')
    class Meta:
        model = User
        fields = ['username', 'email','phone',  'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='שם מלא:')
    email = forms.EmailField(label='כתובת מייל:')
    phone_regex = RegexValidator(regex=r'^\d{9,10}$', message="נא הכנס מספר טלפון כולל קידומת")
    phone = forms.CharField(validators=[phone_regex], max_length=10, label='מספר טלפון:', required=False)
    password = forms.CharField(label='סיסמה:')
    class Meta:
        model = User
        fields = ['username','email', 'phone', 'password']

class ContactForm(forms.ModelForm):
    name = forms.CharField(label='שם מלא:')
    email = forms.EmailField(label='כתובת מייל:')
    phone_regex = RegexValidator(regex=r'^\d{9,10}$', message="נא הכנס מספר טלפון כולל קידומת")
    phone = forms.CharField(validators=[phone_regex], max_length=10, label='מספר טלפון:', required=False)
    title = forms.CharField(label='נושא:')
    message = forms.CharField(widget=forms.Textarea, label='תוכן הפניה:')
    class Meta:
        model = Contact
        fields = ['name','email', 'phone', 'title','message']

class AddressForm(forms.ModelForm):
    town = forms.CharField(label='עיר:')
    street = forms.CharField(label='רחוב:')
    house_num = forms.IntegerField(label='מספר בית:')
    apt_num = forms.IntegerField(label='מספר דירה:')
    level = forms.IntegerField(label='קומה:')
    enter = forms.IntegerField(label='קוד כניסה:', required=False)
    class Meta:
        model = Address
        fields = ['town','street', 'house_num', 'apt_num','level', 'enter']

class ProdUserAddForm(forms.ModelForm):
    amount = forms.IntegerField(label="בחר כמות:")
    weekDay = ((0,'יום ראשון'),(1,'יום שני'),(2,'יום שלישי'),(3,'יום רביעי'),(4,'יום חמישי'),(5,'יום שישי'))

    def get_tmrw():
        weekday = date.now().weekday() # monday is 0 and sunday is 6
        hour = date.now().time().hour
        if weekday==4: #friday
            return 0
        if hour < 20:
            return (weekday+2) % 7
        else:
            return (weekday+3) % 7

    day = forms.ChoiceField(label="היום הנבחר:", choices=weekDay, initial=get_tmrw())
    class Meta:
        model = ProdUser
        fields = ['amount', 'day']

invitations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Contact, Product, Address, ProdUser, BuyHistory
from django.contrib import messages
from django.db import IntegrityError
from .forms import UserRegistrationForm, ContactForm, UserLoginForm, AddressForm, ProdUserAddForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from datetime import datetime as dt
# from rest_framework import viewsets
# from .serializers import AddressSerializer
#
# class AddressViewSet(viewsets.ModelViewSet):
#     queryset = Address.objects.all()
#     serializer_class = AddressSerializer

def home(request):
    content = {}
    return render(request, 'invitations/home.html', content)

def products(request):
    products = Product.objects.all()
    if request.method=='GET':
        return render(request, 'invitations/products.html', {'products': products, 'form': ProdUserAddForm()})
    else:
        try:
            form = ProdUserAddForm(request.POST)
            prodUser = form.save(commit=False)
            prodUser.user = request.user
            prodUser.product = get_object_or_404(Product, pk=request.POST['product'])
            prodUser.save()
            return render(request, 'invitations/products.html', {'products': products, 'form': ProdUserAddForm(), 'message':'הפריט נוסף בהצלחה!'})
        except ValueError:
            return redirect('login')

@login_required
def cart(request):
    myproducts = ProdUser.objects.filter(user=request.user).order_by('day')
    totalPrice = 0
    for prod in myproducts:
        totalPrice += prod.price()
    content = {'content':myproducts, 'Alldays': ProdUser.weekDay, 'sum':totalPrice}

    if request.method == 'GET':
        return render(request, 'invitations/cart.html', content)
    else:
        produser = get_object_or_404(ProdUser, pk=request.POST['produser'])
        action = request.POST.get('what')
        if action == 'remove':
            ProdUser.objects.filter(id=produser.id).delete()
        elif action == 'moveToDay':
            content['form'] = ProdUserAddForm(instance=produser)
            content['action'] = 'moveToDay'
            return render(request, 'invitations/cart.html', content)
        elif action == 'moveToDayData':
            produser.day = request.POST.get('day')
            produser.save()
        elif action == 'copyToDay':
            content['form'] = ProdUserAddForm(instance=produser)
            content['action'] = 'copyToDay'
            return render(request, 'invitations/cart.html', content)
        elif action == 'copyToDayData':
            day = request.POST.get('day')
            amount = request.POST.get('amount')
            if produser.day != day:
                newProduser = ProdUser(day=day, amount=amount, product=produser.product,user=produser.user)
                newProduser.save()
        elif action == 'updateAmount':
            content['form'] = ProdUserAddForm(instance=produser)
            content['action'] = 'updateAmount'
            return render(request, 'invitations/cart.html', content)
        elif action == 'updateAmountData':
            produser.amount = request.POST.get('amount')
            produser.save()
        return redirect('cart')


@login_required
def profil(request):
    if Address.objects.filter(user=request.user):
        content = {'user': request.user, 'address': get_object_or_404(Address, user=request.user), 'addr':1}
        return render(request, 'invitations/profil.html', content)
    else:
        return render(request, 'invitations/profil.html')

@login_required
def address(request):
    if request.method == 'GET':
        if Address.objects.filter(user=request.user):
            oldAddress = get_object_or_404(Address, user=request.user)
            form = AddressForm(instance=oldAddress)
        else:
            form = AddressForm()
        return render(request, 'invitations/address-update.html', {'form': form})
    else:
        try:
            if Address.objects.filter(user=request.user):
                oldAddress = get_object_or_404(Address, user=request.user)
                form = AddressForm(request.POST, instance=oldAddress)
                form.save()
            else:
                form = AddressForm(request.POST)
                address = form.save(commit=False)
                address.user = request.user
                address.save()
            return redirect('profil')
        except ValueError:
            return render(request, 'invitations/address-update.html', {'form': AddressForm(), 'error':'כתובת לא מתאימה'})

@login_required
def history(request):
    histories = BuyHistory.objects.filter(user=request.user)
    priceForThisMonth = 0
    for prod in histories.filter(date__month=dt.now().month):
        priceForThisMonth += prod.price()
    content = {'histories':histories, 'priceForThisMonth':priceForThisMonth}
    return render(request, 'invitations/history.html',content)

@login_required
def checkout(request):
    if Address.objects.filter(user=request.user):
        address = get_object_or_404(Address, user=request.user)
        addressForm = AddressForm(instance=address)
    else:
        addressForm = AddressForm()
    return render(request, 'invitations/checkout.html', {'address':addressForm})
    
def contact(request):
    if request.user.is_authenticated:
        initial = {
            'name': request.user.username,
            'email': request.user.email,
            'phone': request.user.phone
        }
    else:
        initial = None
    if request.method == 'GET':
        return render(request, 'invitations/contact.html', {'form': ContactForm(initial=initial)})
    else:
        try:
            form = ContactForm(request.POST)
            form.save()
            return redirect('home')
        except ValueError:
            return render(request, 'invitations/contact.html', {'form': ContactForm(initial=initial)})

    
def usersignup(request):
    if request.method == 'GET':
        return render(request, 'invitations/user-signup.html', {'form': UserRegistrationForm()})
    else:
        # create a new user
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'],email=request.POST['email'],phone=request.POST['phone'])
                login(request, user)
                return redirect('cart')
            except IntegrityError:
                return render(request, 'invitations/user-signup.html',
                              {'form': UserRegistrationForm(), 'error': 'השם הזה קיים.. נדאג שיאפשר שמות כפולים'})
        else:
            # tell the user that password didnt match
            return render(request, 'invitations/user-signup.html',
                          {'form': UserRegistrationForm(), 'error': 'הסיסמאות אינם תואמות'})


def userlogin(request):
    if request.method == 'GET':
        return render(request, 'invitations/user-login.html', {'form': UserLoginForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'],email=request.POST['email'],phone=request.POST['phone'])
        if user is None:
            return render(request, 'invitations/user-login.html',
                          {'form': UserLoginForm(), 'error': 'שם המשתמש או הסיסמה אינם נכונים.. נסה שוב'})
        else:
            login(request, user)
            return redirect('cart')

@login_required
def userlogout(request):
    # print(request,'/n')
    # dir(request)
    if request.method == 'POST':
        # if it would be get request, some browsers load the href urls of the page in order to make it faster, then it will log me out without clicking on logout
        logout(request)
        return redirect('home')

def about(request):
    content = {}
    return render(request, 'invitations/about.html', content)

invitations/templates/invitations/about.html
{% extends 'invitations/base.html' %}
{% block content %}
<h3>about</h3>
{% endblock %}

invitations/templates/invitations/address-update.html
{% extends 'invitations/base.html' %}
{% block content %}
<h3 class="title">עדכון כתובת</h3>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset>{{form.as_p}}</fieldset>
        <div class="btn-wrapper">
        <button class="color-btn" type="submit">אישור</button>
        </div>
    </form>
</div>
{% endblock %}

invitations/templates/invitations/base.html
<!doctype html>
<html lang="he">
	{% load static %}
	<head>
			<meta charset="UTF-8">
			<meta name="viewport" content="content-width-device, initial-scale=1,maximum-scale=1, minimum-scale=1"/>
			<title>ריח הבוקר</title>
		 	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"-->
			<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	</head>

	<body dir=rtl>
	<header>
		<nav>
			<div class="menu-wrapper">
			    <h1 class="menu-btn">פעולות&gt;</h1>
				<ul class="menu-content">
					<li><a href="{% url 'home' %}" class="menu-elem">ראשי</a></li>
					<li><a href="{% url 'products' %}" class="menu-elem">בחירת מוצרים</a></li>
					<li><a href="{% url 'contact' %}" class="menu-elem">צור קשר</a></li>
				    {% if user.is_authenticated %}
					<li><a href="{% url 'profil' %}" class="menu-elem">הפרטים שלי</a></li>
					<li><a href="{% url 'cart' %}" class="menu-elem">הסל שלי</a></li>
					<li><a href="{% url 'history' %}" class="menu-elem">היסטוריה</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
		<div class="logo"><img width="250px" src="{% static 'images/logomorningsmell.png' %}"></div>
		{% if user.is_authenticated %}
        <form class = "left-btn" action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <div class="btn-wrapper">החשבון של {{user}}</div>
			<div class="btn-wrapper"><button type="submit" class="color-btn">התנתק</button></div>
        </form>

		{% else %}
		<div class="left-btn">
		    <div class="btn-wrapper"><a href="{% url 'login' %}" class="color-btn">כניסה</a></div>
			<div class="btn-wrapper"><a href="{% url 'signup' %}" class="color-btn">הרשמה</a></div>
		</div>
		{% endif %}
	</header>

	<div class="content">
		{% block content %} {% endblock %}
	</div>
	</body>
</html>

invitations/templates/invitations/cart.html
{% extends 'invitations/base.html' %}
{% block content %}
{% load static %}
<h3 class = "title">התפריט שלי</h3>
{% regroup content by day as daysList %}

<ul>
    {% for day in daysList %}
        <li>
            <h3>{{day.list.0.get_day_display}}</h3>
            <ul>
            {% for produser in day.list %}
                <li class = "cart-item-name"><br>
                    <b>{{ produser.product.product_name }}</b>
                    <div class="cart-item">
                        <img src="{{ produser.product.picture.url }}" width="100px" height="100px" alt=""><br>
                        <h6>מחיר: {{ produser.product.price }}</h6>
                        <h6>כמות: {{ produser.amount }}</h6>
                        <h6>סה"כ: {{ produser.price }}</h6>

                        <div class="cart-actions">
                            <div>
                                <form href="{% url 'cart' %}" method ="POST">
                                {% csrf_token %}
                                <input name="produser" type="hidden" value="{{produser.id}}">
                                <input name="what" type="hidden" value='remove'>
                                <button class="mybtn" type="submit" >מחק מהיום</button>
                                </form>

                                                            <form href="{% url 'cart' %}" method ="POST">
                                {% csrf_token %}
                                <input name="produser" type="hidden" value="{{produser.id}}">
                                <input name="what" type="hidden" value='updateAmount'>
                                <button class="mybtn" type="submit" >שינוי כמות</button>
                                </form>
                                {% if form.instance == produser and action == 'updateAmount' %}
                                <form href="{% url 'cart' %}" method ="POST">
                                    {% csrf_token %}
                                    <fieldset display="block" class="add">{{form.amount}}</fieldset>
                                    <input name="what" type="hidden" value='updateAmountData'>
                                    <input name="produser" type="hidden" value="{{produser.id}}">
                                    <button class="mybtn" type="submit" >שמור</button>
                                </form>
                                {% endif %}
                            </div>

                            <div>
                                <form href="{% url 'cart' %}" method ="POST">
                                {% csrf_token %}
                                <input name="produser" type="hidden" value="{{produser.id}}">
                                <input name="what" type="hidden" value='moveToDay'>
                                <button class="mybtn" type="submit" >העבר יום</button>
                                </form>
                                {% if form.instance == produser and action == 'moveToDay' %}
                                <form href="{% url 'cart' %}" method ="POST">
                                    {% csrf_token %}
                                    <fieldset display="block" class="add">{{form.day}}</fieldset>
                                    <input name="what" type="hidden" value='moveToDayData'>
                                    <input name="produser" type="hidden" value="{{produser.id}}">
                                    <button class="mybtn" type="submit" >שמור</button>
                                </form>
                                {% endif %}

                                <form href="{% url 'cart' %}" method ="POST">
                                {% csrf_token %}
                                <input name="produser" type="hidden" value="{{produser.id}}">
                                <input name="what" type="hidden" value='copyToDay'>
                                <button class="mybtn" type="submit" >העתק ליום</button>
                                </form>
                                {% if form.instance == produser and action == 'copyToDay' %}
                                <form href="{% url 'cart' %}" method ="POST">
                                    {% csrf_token %}
                                    <fieldset display="block" class="add">{{form.as_p}}</fieldset>
                                    <input name="what" type="hidden" value='copyToDayData'>
                                    <input name="produser" type="hidden" value="{{produser.id}}">
                                    <button class="mybtn" type="submit" >שמור</button>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
            </ul>
            <hr>
        </li>
    {% endfor %}
</ul>
<h1  class="title">סך הכל לשבוע:</h1>
<h4>{{sum}} ש"ח</h4>
<br>
<a href="{% url 'checkout' %}" class="mybtn" >אישור הזמנה</a>
<script src="{% static 'javascript/cart.js' %}"></script>
{% endblock %}

invitations/templates/invitations/checkout.html
{% extends 'invitations/base.html' %}
{% block content %}
<form method="POST">
    <h3 class="title">הכתובת שלך</h3>
    {% csrf_token %}
    <fieldset>{{address.as_p}}</fieldset>
    <h3 class="title">פרטי אשראי</h3>
    <input>
    <div class="btn-wrapper">
    <button class="color-btn" type="submit">אישור</button>
    </div>
</form>
{% endblock %}

invitations/templates/invitations/contact.html
{% extends 'invitations/base.html' %}
{% block content %}
<h1 class="title">יצירת קשר</h1>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset>{{form.as_p}}</fieldset>
        <div class="btn-wrapper">
        <button class="color-btn" type="submit">אישור</button>
        </div>
    </form>
</div>
{% endblock %}

invitations/templates/invitations/history.html
{% extends 'invitations/base.html' %}
{% block content %}
<h3 class="title">היסטוריה</h3>
{% regroup histories|dictsortreversed:"date" by date|date:"F" as history_monthes %}
    {% for month in history_monthes %}
    <br><hr>
    {% now "F" as this_month %}
    {% if month.grouper == this_month %}
    <h3>החודש הנוכחי</h3>
    {% else %}
    <h3>{{month.grouper}}</h3>
    {% endif %}
        {% for history in month.list %}
        <div class="history-item">
            <div><b>{{history.product.product_name}}</b><br>
            <img src="{{ history.product.picture.url }}" width="100px" height="100px" alt=""></div>
            <div class="history-details"><h6>מחיר: {{ history.product.price }}</h6>
            <h6>כמות: {{ history.amount }}</h6>
            <h6>סה"כ: {{ history.price }}</h6>
            <h6>תאריך: {{ history.date|date:"d F, Y" }}</h6></div>
        </div>
        {%endfor%}
        {% if month.grouper == this_month %}
        <br><br><h5> לתשלום החודש: {{priceForThisMonth }}</h5>
        {% endif %}
    {%endfor%}
{% endblock %}

invitations/templates/invitations/home.html
{% extends 'invitations/base.html' %}
{% block content %}
{% load static %}
    <img width="10%" src="{% static 'images/left-arrow.png' %}" alt="">
    <img width="75%" src="{% static 'images/bread1.png' %}" alt="">
    <img width="10%" src="{% static 'images/right-arrow.png' %}" alt="">
    <h1 class="what">לחמניות טריות ודברי חלב כל בוקר עד דלת ביתך..</h1>
    <div class="how">
    <h1>איך זה עובד?<br>פשוט נכנסים לבחירת מוצרים, בוחרים תפריט יומי, מעדכנים את הפרטים ובבוקר מגיע השליח עם ארוחת הבוקר..</h1>
        <div class="btn-wrapper">
        <a class="color-btn" href="{% url 'products' %}">לבחירת מוצרים</a>
        </div>
    </div>
{% endblock %}

invitations/templates/invitations/products.html
{% extends 'invitations/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<div class="row">
	{% if message %}
		<p>{{message}}</p>
		<a href="{% url 'cart' %}">לצפייה בתפריט</a>
	{% endif %}
	{% regroup products by category as catList %}
	{% for cat in catList %}
		<h1  class="title">{{ cat.list.0.get_category_display }}</h1>
		{% for product in cat.list %}
		<div class="col-lg-4">
			<div class="box-element">
			<img class="image" src="{{ product.picture.url }}" width="200px" height="200px" alt="">
			<div class="under-pic">
				<p>{{product.product_name}}</p>
				<p>{{product.price}}</p>
				<form action="{% url 'products' %}" method ="POST">
					{% csrf_token %}
					<fieldset display="block" class="add">{{form.as_p}}</fieldset>
					<input name="product" type="hidden" value="{{product.id}}">
					<button class="mybtn" type="submit" >הוסף לסל</button>
				</form>
			</div>
			</div>
		</div>
		{% endfor %}
	{% endfor %}


{% endblock %}

invitations/templates/invitations/profil.html
{% extends 'invitations/base.html' %}
{% block content %}
<h3 class="title">פרטי הפרופיל שלי</h3>
<div class="content-section">
    <b>שם משתמש:</b><p>{{user.username}}</p>
    <b>כתובת מייל:</b><p>{{user.email}}</p>
    {% if user.phone %}
    <b>מספר טלפון:</b><p>{{user.phone}}</p>
    {% endif  %}
</div>
{% if addr %}
<div class="content-section">
    <b>כתובת:</b>
    <ul>
    {% for name, value in address.get_fields %}
    {% if value != 'None' and name != 'ID' and name != 'user' %}
        <li>{{name}}: {{value}}</li>
    {% endif %}
    {% endfor %}
    </ul>
</div>
{% endif %}
<a href="{% url 'address-update' %}">עדכון כתובת</a>
{% endblock %}

invitations/templates/invitations/user-login.html
{% extends 'invitations/base.html' %}
{% block content %}
<h1 class="title">כניסה</h1>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset>{{form.as_p}}</fieldset>
        <div class="btn-wrapper">
        <button class="color-btn" type="submit">אישור</button>
        </div>
    </form>
</div>
    <a href="{% url 'signup' %}">עוד לא נרשמת? הרשם </a>
{% endblock %}

invitations/templates/invitations/user-signup.html
{% extends 'invitations/base.html' %}
{% block content %}
<h1 class="title">הרשמה</h1>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset>{{form.as_p}}</fieldset>
        <div class="btn-wrapper">
        <button class="color-btn" type="submit">אישור</button>
        </div>
    </form>
</div>
{% endblock %}